# Generated by Django 4.2.16 on 2024-10-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'manager'), (2, 'employee')], default=0),
        ),
    ]
