# Generated by Django 4.2.16 on 2024-10-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_code'),
        ('ordermanagement', '0002_alter_customer_customer_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=0)),
                ('order_date', models.DateField()),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('bill', models.FloatField(default=0)),
                ('Customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.customer')),
                ('product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
    ]
